### PR TITLE
demo how to mock (#86)

### LINKED ISSUE #86: Needs to mock padchat-manager inside puppet-padchat
I would like to know how to mock the private property `padchat-manager` inside `puppet-padchat`. And I would like to only mock one method on `padchat-manager`, which is the `WXGetContactPayload`. 

Do you know any way to do this?

### PR DESCRIPTION
**Pull request by zixia**
fix #86

### CODE REVIEW

**Comment by windmemory** [comment]
Can you run this test? I tried to run it, and got such error:
```shell
src/puppet-padchat.spec.ts:10:7 - error TS2415: Class 'PuppetPadchatTest' incorrectly extends base class 'PuppetPadchat'.
  Property 'padchatManager' is private in type 'PuppetPadchat' but not in type 'PuppetPadchatTest'.

10 class PuppetPadchatTest extends PuppetPadchat {
```

**Comment by zixia** [comment]
Please try to reverse my last commit and try again.

If you still have any problem to run this, please:

1. put your logic to the code to demonstrate what you want to do exactly
1. run the code with the error message, and try to fix it by yourself
1. if you can not get it done, please let me know after you finish 1 & 2, I'll fix it for you later.

**Comment by windmemory** [comment]
I did added some code, but it doesn't work as expected. Because the `puppet-padchat` and `padchat-manager` initialize needs a lot of operations. I tried to fill some hole of the process, but still not able to run my testcase. Here is my test:

```javascript
test('PuppetPadchat() should return false for contactPayload with no user_name', async t => {
  let wrappedCheckQRCode = false;
  const FAKE_ID = 'fakeId'
  const FAKE_WX_CHECK_QR_CODE: WXCheckQRCodePayload = {
    "expired_time": 236,
    "head_url": "http://wx.qlogo.cn/mmhead/ver_1/5VaXXlAx53wb3M46gQpVtLiaVMd4ezhxOibJiaZXLf2ajTNPZloJI7QEpVxd4ibgpEnLF8gHVuLricaJesjJpsFiciaOw/0",
    "nick_name": "李卓桓",
    "status": 1
  }

  const puppet = new PuppetPadchatTest({
    token: 'test-token',
  })

  const sandbox = sinon.createSandbox()

  await puppet.start()

  puppet.on('scan', (qrcode, status, data) => {
    if (!wrappedCheckQRCode) {
      const mockWXCheckQRCode = () => {
        return FAKE_WX_CHECK_QR_CODE
      }
    
      const fakeCheckQRCode = sandbox.stub(puppet.padchatManager!, 'WXCheckQRCode')
                                     .callsFake(mockWXCheckQRCode)
      
      wrappedCheckQRCode = true
    }
  })

  puppet.on('login', contactId => {
    t.ok(true, 'logged in')
    
    const mockWXGetContactPayload = (id: string) => {
      return { id } as any
    }
    const fakeContactPayload = sandbox.stub(puppet.padchatManager!, 'WXGetContactPayload')
                                      .callsFake(mockWXGetContactPayload)
  
    const validateResult = puppet.contactValidate(FAKE_ID)
    t.ok(fakeContactPayload.called, 'should call WXGetContactPayload')
    t.ok(!validateResult, 'validate result should be false')

    puppet.logout()
  })

  puppet.on('logout', contactId => {
    sandbox.restore()
  })
})

```
The error log below:
```shell
# PuppetPadchat() should return false for contactPayload with no user_name
13:28:32 WARN PuppetPadchatManager startCheckScan() unknown WXCheckQRCodeStatus: -2
13:29:33 WARN PadchatRpc initWebSocket() ws.on(close) 1005
13:29:33 WARN PuppetPadchat startManager() manager.on(reset) for ws.on(close, 1005. Restarting PuppetPadchat ... 
13:29:33 WARN PuppetPadchat logout() this.id not exist
```

I think I might need to mock the socket also, besides, some socket events are also needed to run the test, seems like this is beyond the unit test scope, more like a integration test.

**Comment by zixia** [comment]
Unfortunately, I feel you misunderstand the purpose of my PR: What I want to demonstrate to you is how to do the mock job, not to finish the unit test for you.

It seems very good that you start to know how to run the code that I demonstrated to you. 

Mock is very easy, but make the unit tests work as you expected is not that easy. You have to dive into the design of the code, understand the module, design the right pattern so that you will be able to make it testable.

Next, please help yourself to finish other dirty works other than my demo, I believe you could finish it soon after investigate some time, and it will be very valuable for you to be able to mock this module because it will really help you a lot in the near future.

**Comment by zixia** [comment]
One more thing: yes, it is an integration test.

1. Unit Tests will be put into the same directory as the source code, like src/
1. Integration Tests will be put into the tests/ directory.

**Comment by windmemory** [comment]
Okay, let's close this PR. I will submit the IT later in my last PR.

**Comment by zixia** [comment]
My suggestion is that the best practice is to never close a PR and re-create a new one.

Because that will lost lots of useful information, like valuable discussions, and very hard to trace.

**Comment by windmemory** [comment]
I am not recreating a new one, I had one here: https://github.com/lijiarui/wechaty-puppet-padchat/pull/84

And to my understanding, closing a PR is not deleting a PR, we are not losing anything, it's just remove this from the opened PR list.

**Comment by zixia** [comment]
Ok, I understand, then there's no problem any more.

It's better to link to the old one by a comment like:

Merge to #84

**Comment by windmemory** [comment]
Okay, got it. Will use `Merge to #num` next time

**Comment by zixia** [comment]
Great, thanks!

**Pull request closed without merging**
