### PR TITLE
fix #81 undefined user name issue

### LINKED ISSUE #81: Can not get contact payload
refer to https://github.com/Chatie/wechaty/issues/1396

### PR DESCRIPTION
**Pull request by windmemory**

### CODE REVIEW

**Comment by zixia** [comment]
Can you provide the related Unit Test? Because only that we can confirm the code behavior is right.

**Comment by windmemory** [comment]
Sure, will add some later.

**Comment by zixia** [comment]
Great. So let's postpone this discussion before we had those unit test.

**Comment by windmemory** [comment]
After digging into the test case we already have in puppet-padchat, to write a unit test to cover this logic is very difficult. Since testing this logic needs to mock the `padchat-manager`'s behavior, and needs to only mock part of the behavior. Besides, `padchat-manager` is a private property of `puppet-padchat`, mocking a private property is also very hard. 

So can we just talk about the logic of the code and test it in runtime? Since this is fixing a frequent appearing error, I think it would be better to pushed soon.

**Comment by zixia** [comment]
It should be easy instead of difficult if you are using the right tools with the right pattern.

See my reply in #86 and the PR #87

**Comment by windmemory** [comment]
I added the integration tests. There are some points that I am not pretty sure, so correct me if I am wrong. 

I added the change that I think it would stop writing empty `contactPayload` into the cache in `padchat-manager`. I put a test case that I try to validate a contact which is invalid, then check the validate results, and also get the `contactList` to see whether the contact has been added to the list. 

I assume that a contact is not null, but has no `user_name` is invalid, so in the `contactRawPayload`  method, I returned null for this case. The reason that I change it because I observed that if the `tryRawPayload` verification failed, it would do a retry on this contact, and the retry failed after 9 retries, and it will last about 1 min. I think if we get the response from the server and the response is not null or undefined, then it's not a recoverable error, so I made such change. 

But I am not 100% understanding the whole wechaty flow, please correct me if I am wrong.

**Comment by zixia** [comment]
This PR seems wired.

Why it includes many changes which I did before?

**Comment by windmemory** [comment]
Because I rebased the branch and then pushed.

**Comment by zixia** [comment]
You should only include what you change in your PR, or I can not review it because they are not related.

**Comment by windmemory** [comment]
I don't want to include these changes either. But to make sure my code works with the newest version, I need to merge the changes to my branch, deal with the conflict, then push it. 

If I don't merge these changes, then my changes might not work with the latest version. 

To deal with the issue here, I would suggest to open another PR with a base of the latest version, then cherry-pick my change to that branch, then delete this one. Is that okay for you?

**Comment by windmemory** [comment]
merge to #88

**Pull request closed without merging**
