### PR TITLE
Mentions

### PR DESCRIPTION
**Pull request by lhr0909**

### CODE REVIEW

**Comment by lhr0909** [comment]
This is still not working, sending in the logs for debugging purposes on the Padchat RPC layer.

```
19:12:39 VERB Room say(LOLOLO YAPMAA BAANA, Simon Liang)
19:12:39 VERB PuppetPadchat messageSend({"contactId":"wxid_1602626028312","roomId":"12434145320@chatroom"}, @Simon Liang LOLOLO YAPMAA BAANA, wxid_1602626028312)
19:12:39 SILL PadchatRpc rpcCall(WXSendMsg, ["12434145320@chatroom","@Simon Liang LOLOLO YAPMAA BAANA","wxid_1602626028312"])
19:12:40 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXSendMsg","data":"%7B%22message%22%3A%22%22%2C%22msg_id%22%3A%224971659805816872978%22%
19:12:40 SILL PadchatRpc generateBaseMsg(4971659805816872978, 12434145320@chatroom) {"content":"","continue":0,"description":"","from_user":"wxid_9kdvx1gsny6z22","msg_id":"4971659805816872978","msg_source":"","msg_type":5,"status":1,"sub_type":49,"timestamp":1543576360.642,"to_user":"12434145320@chatroom","uin":0}
19:12:40 SILL PadchatRpc replayTextMsg replaying message: {"content":"@Simon Liang LOLOLO YAPMAA BAANA","continue":0,"description":"","from_user":"wxid_9kdvx1gsny6z22","msg_id":"4971659805816872978","msg_source":"","msg_type":5,"status":1,"sub_type":1,"timestamp":1543576360.642,"to_user":"12434145320@chatroom","uin":0}
19:12:40 VERB PuppetPadchat onPadchatMessage({id=4971659805816872978, type=Text(5)})
19:12:40 VERB Message static load(4971659805816872978)
19:12:40 SILL Accessory #10<Message> constructor()
19:12:40 VERB Message constructor(4971659805816872978) for class Message
19:12:40 VERB Message ready()
19:12:40 VERB Puppet messagePayload(4971659805816872978)
19:12:40 SILL Puppet messagePayloadCache(4971659805816872978) cache MISS
19:12:40 VERB PuppetPadChat messageRawPayloadParser({msg_id="4971659805816872978"})
19:12:40 SILL PuppetPadchat messagePayload({"id":"4971659805816872978","timestamp":1543576360.642,"type":7,"fromId":"wxid_9kdvx1gsny6z22","roomId":"12434145320@chatroom","text":"@Simon Liang LOLOLO YAPMAA BAANA"})
```

**Comment by windmemory** [comment]
The mention list is just missing when rpc layer try to replay the message. Can you receive the notification when the message sent out?

**Comment by lhr0909** [comment]
@windmemory no we did not receive any mention notifications

**Comment by lhr0909** [comment]
image

No luck after properly testing it.

**Comment by windmemory** [comment]
I will try to test this with your change this weekend. Will get back to you later.

**Comment by windmemory** [comment]
I am merging this commit, and will append some fix to make this work after this get merged. Thanks for the contribution!

**Pull request merged**
